export const LOADING_START = 'LOADING_START';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOADING_ERROR = 'LOADING_ERROR';
export const SET_LOADING_MESSAGE = 'SET_LOADING_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';