export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const CHANGE_CHARACTER_STATS = 'CHANGE_CHARACTER_STATS';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';